services:
  hytale:
    image: debian:13-slim
    container_name: hytale-server
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "5520:5520/udp"
    volumes:
      - ./data:/data
      - ./container-scripts:/scripts
      - /etc/machine-id:/etc/machine-id:ro
    working_dir: /data
    command: ["/scripts/bootstrap.sh"]
